# Install Space Dropdown into the active Zen profile (Windows).
# Zen's Mods "Import" only works for official store mods — use this instead.

$ErrorActionPreference = "Stop"
$modId = "a1c8e4f2-9b3d-4e7a-8f1c-2d6b5a9e0c44"
$repo = $PSScriptRoot

$profilesIni = Join-Path $env:APPDATA "zen\profiles.ini"
if (-not (Test-Path $profilesIni)) {
  throw "Zen profiles.ini not found at $profilesIni"
}

$ini = Get-Content $profilesIni
$defaultPath = $null
$pathMap = @{}
$current = $null
foreach ($line in $ini) {
  if ($line -match '^\[(.+)\]') { $current = $Matches[1]; continue }
  if ($null -eq $current) { continue }
  if ($line -match '^Path=(.+)$') { $pathMap[$current] = $Matches[1] }
  if ($line -match '^Default=1$' -and $current -like 'Profile*') {
    $defaultPath = $pathMap[$current]
  }
}
if (-not $defaultPath) {
  # Fall back to Install Default=
  foreach ($line in $ini) {
    if ($line -match '^Default=Profiles/(.+)$') { $defaultPath = "Profiles/$($Matches[1])"; break }
  }
}
if (-not $defaultPath) { throw "Could not resolve Zen profile path" }

$profile = if ([System.IO.Path]::IsPathRooted($defaultPath)) {
  $defaultPath
} else {
  Join-Path $env:APPDATA "zen\$defaultPath"
}

Write-Host "Profile: $profile"
$dest = Join-Path $profile "chrome\zen-themes\$modId"
New-Item -ItemType Directory -Path $dest -Force | Out-Null
Copy-Item (Join-Path $repo "chrome.css") (Join-Path $dest "chrome.css") -Force
Copy-Item (Join-Path $repo "preferences.json") (Join-Path $dest "preferences.json") -Force

$themesPath = Join-Path $profile "zen-themes.json"
$themes = if (Test-Path $themesPath) {
  Get-Content $themesPath -Raw | ConvertFrom-Json
} else {
  [pscustomobject]@{}
}

$entry = [pscustomobject]@{
  id          = $modId
  name        = "Space Dropdown"
  description = "Compact Spaces dropdown for expanded sidebar."
  homepage    = "https://github.com/B0tis/zen-space-dropdown"
  style       = "https://raw.githubusercontent.com/B0tis/zen-space-dropdown/master/chrome.css"
  readme      = "https://raw.githubusercontent.com/B0tis/zen-space-dropdown/master/README.md"
  image       = "https://raw.githubusercontent.com/B0tis/zen-space-dropdown/master/preview.png"
  author      = "B0tis"
  version     = "1.1.0"
  tags        = @("workspaces", "sidebar", "spaces")
  createdAt   = "2026-08-12"
  updatedAt   = (Get-Date -Format "yyyy-MM-dd")
  preferences = "https://raw.githubusercontent.com/B0tis/zen-space-dropdown/master/preferences.json"
  enabled     = $true
}

$themes | Add-Member -NotePropertyName $modId -NotePropertyValue $entry -Force
$themes | ConvertTo-Json -Depth 10 | Set-Content -Path $themesPath -Encoding UTF8

# Rebuild aggregated stylesheet from enabled mods
$chromeDir = Join-Path $profile "chrome"
New-Item -ItemType Directory -Path $chromeDir -Force | Out-Null
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Generated by install.ps1 for Space Dropdown */")
foreach ($prop in $themes.PSObject.Properties) {
  $mod = $prop.Value
  if (-not $mod.enabled) { continue }
  $modCss = Join-Path $profile "chrome\zen-themes\$($mod.id)\chrome.css"
  if (Test-Path $modCss) {
    [void]$sb.AppendLine("/* Start Theme: $($mod.name) */")
    [void]$sb.AppendLine((Get-Content $modCss -Raw))
    [void]$sb.AppendLine("/* End Theme: $($mod.name) */")
  }
}
Set-Content -Path (Join-Path $chromeDir "zen-themes.css") -Value $sb.ToString() -Encoding UTF8

# Ensure prefs exist
$userJs = Join-Path $profile "user.js"
$prefLines = @(
  'user_pref("mod.space-dropdown.enabled", true);',
  'user_pref("mod.space-dropdown.show_names", true);',
  'user_pref("mod.space-dropdown.max_height", "280px");',
  'user_pref("mod.space-dropdown.chip_radius", "8px");'
)
$kept = @()
if (Test-Path $userJs) {
  $kept = Get-Content $userJs | Where-Object { $_ -notmatch 'mod\.space-dropdown\.' }
}
Set-Content -Path $userJs -Value (($kept + $prefLines) -join "`n") -Encoding UTF8

Write-Host "Installed Space Dropdown."
Write-Host "Restart Zen, or open Settings → Mods and toggle the mod off/on."
